export function isUrdu(locale: string) {
  return locale === "ur";
}

export const tourCopy = {
  en: {
    steps: ["Details", "Hotels", "Flights", "Review"],
    nav: {
      previous: "Previous",
      next: "Next Step",
      sending: "Sending...",
      submit: "Submit Quotation",
      submissionFailed: "Submission failed. Please try again.",
      genericError: "Something went wrong. Please try again.",
    },
    errors: {
      passengerName: "Please enter the passenger name.",
      contactNumber: "Please enter a valid contact number.",
      email: "Please enter a valid email address.",
      countries: "Add at least one country.",
      country: "Select a country.",
      hotelName: "Enter hotel name.",
      checkIn: "Select check-in.",
      checkOut: "Select check-out.",
      dateOrder: "Check-out must be after check-in.",
      flights: "Add at least one flight.",
      airline: "Select airline.",
      departureCity: "Select departure city.",
      destination: "Select destination.",
      date: "Select date.",
    },
    step1: {
      step: "Step 1",
      title: "Customer & Passenger Details",
      description:
        "Enter the lead passenger's contact info and the total number of travellers.",
      passengerName: "Passenger Name",
      passengerPlaceholder: "Lead passenger name",
      contactNumber: "Contact Number",
      email: "Email Address",
      groups: [
        ["Adults", "Age 12+"],
        ["Children", "Age 2-11"],
        ["Infants", "Under 2 (lap)"],
      ],
    },
    step2: {
      step: "Step 2",
      title: "Tour Countries & Hotels",
      description: "Add each destination country and the hotels you plan to stay in.",
      addCountry: "Add Another Country",
      total: "Total",
      nightsAcross: "Nights across",
      destinations: "destination(s)",
      destination: "Destination",
      country: "Country",
      selectCountry: "Select Country",
      addHotel: "Add Another Hotel",
      removeDestination: "Remove destination",
      hotel: "Hotel",
      removeHotel: "Remove hotel",
      hotelName: "Hotel Name",
      hotelPlaceholder: "Hotel name",
      pricePerNight: "Price per Night",
      pricePlaceholder: "PKR per night",
      checkIn: "Check-in Date",
      checkOut: "Check-out Date",
      nights: "Nights",
      dateOrder: "Check-out must be after check-in.",
    },
    step3: {
      step: "Step 3",
      title: "Flight Destinations & Ticket Pricing",
      description: "Add each flight leg and enter per-person ticket prices.",
      addFlight: "Add Another Flight",
      totalTicket: "Total Ticket Cost (all flights)",
      flight: "Flight",
      removeFlight: "Remove flight",
      airline: "Airline",
      selectAirline: "Select Airline",
      from: "From (departure)",
      selectDeparture: "Select Departure City",
      to: "To (destination)",
      selectDestination: "Select Destination",
      date: "Date",
      time: "Time",
      ticketPrices: "Ticket Prices (PKR per person)",
      perAdult: "Per Adult",
      perChild: "Per Child",
      perInfant: "Per Infant",
      adultPlaceholder: "PKR per adult",
      childPlaceholder: "PKR per child",
      infantPlaceholder: "PKR per infant",
      adults: "Adults",
      children: "Children",
      infants: "Infants",
      flightTotal: "Flight Total",
    },
    review: {
      title: "Review Your Tour Quotation",
      description:
        "Review all details carefully before submitting. Our team will contact you within 2 business hours.",
      couponTitle: "Coupon Code (Optional)",
      couponPlaceholder: "Enter coupon code if you have one",
      couponNote: "Coupon discounts are applied manually by The Flight Centre team.",
      customer: "Customer Details",
      name: "Name",
      contact: "Contact",
      email: "Email",
      passengers: "Passengers",
      adults: "Adults",
      children: "Children",
      infants: "Infants",
      age12: "Age 12+",
      age2to11: "Age 2-11",
      under2: "Under 2",
      totalPassengers: "Total Passengers",
      countriesHotels: "Countries & Hotels",
      selectedCountry: "Selected Country",
      hotelName: "Hotel Name",
      notProvided: "Not provided",
      checkInOut: "Check-in - Check-out",
      nights: "Nights",
      nightsLower: "nights",
      rate: "Rate",
      night: "night",
      hotelCost: "Hotel Cost",
      countryFallback: "Country",
      subtotal: "Subtotal",
      totalHotelNights: "Total Hotel Nights",
      totalHotelCost: "Total Hotel Cost",
      flights: "Flights",
      flight: "Flight",
      airline: "Airline",
      date: "Date",
      adultTickets: "Adult Tickets",
      childTickets: "Child Tickets",
      infantTickets: "Infant Tickets",
      flightTotal: "Flight Total",
      totalFlightCost: "Total Flight Cost",
      coupon: "Coupon",
      couponCode: "Coupon Code",
      none: "None",
      discountNote: "Discount will be applied by The Flight Centre team.",
      totalSummary: "Total Quotation Summary",
      grandTotal: "Grand Total",
      estimateNote:
        "This is an estimated quotation based on the rates you have entered. Final pricing will be confirmed by The Flight Centre team. Hotel and flight availability subject to change.",
    },
    success: {
      title: "Tour Quotation Submitted!",
      description:
        "Your tour package quotation has been received. Our travel team will contact you within 2 business hours with pricing and availability.",
      reference: "Reference Number",
      call: "We'll call",
      confirmation: "Confirmation sent to",
      returning: "Returning to homepage in",
      goHome: "Go Home Now",
    },
  },
  ur: {
    steps: ["تفصیلات", "ہوٹلز", "فلائٹس", "جائزہ"],
    nav: {
      previous: "واپس",
      next: "اگلا مرحلہ",
      sending: "بھیجا جا رہا ہے...",
      submit: "کوٹیشن جمع کریں",
      submissionFailed: "درخواست جمع نہیں ہو سکی۔ دوبارہ کوشش کریں۔",
      genericError: "کچھ مسئلہ پیش آیا۔ براہِ کرم دوبارہ کوشش کریں۔",
    },
    errors: {
      passengerName: "براہِ کرم مسافر کا نام درج کریں۔",
      contactNumber: "براہِ کرم درست رابطہ نمبر درج کریں۔",
      email: "براہِ کرم درست ای میل ایڈریس درج کریں۔",
      countries: "کم از کم ایک ملک شامل کریں۔",
      country: "ملک منتخب کریں۔",
      hotelName: "ہوٹل کا نام درج کریں۔",
      checkIn: "چیک اِن منتخب کریں۔",
      checkOut: "چیک آؤٹ منتخب کریں۔",
      dateOrder: "چیک آؤٹ تاریخ چیک اِن کے بعد ہونی چاہیے۔",
      flights: "کم از کم ایک فلائٹ شامل کریں۔",
      airline: "ایئر لائن منتخب کریں۔",
      departureCity: "روانگی کا شہر منتخب کریں۔",
      destination: "منزل منتخب کریں۔",
      date: "تاریخ منتخب کریں۔",
    },
    step1: {
      step: "مرحلہ 1",
      title: "کسٹمر اور مسافر کی تفصیلات",
      description: "مرکزی مسافر کی رابطہ معلومات اور کل مسافروں کی تعداد درج کریں۔",
      passengerName: "مسافر کا نام",
      passengerPlaceholder: "مرکزی مسافر کا نام",
      contactNumber: "رابطہ نمبر",
      email: "ای میل ایڈریس",
      groups: [
        ["بالغ", "عمر 12+"],
        ["بچے", "عمر 2 تا 11"],
        ["شیرخوار", "2 سال سے کم"],
      ],
    },
    step2: {
      step: "مرحلہ 2",
      title: "ٹور ممالک اور ہوٹلز",
      description: "ہر منزل کا ملک اور وہ ہوٹلز شامل کریں جہاں آپ قیام کرنا چاہتے ہیں۔",
      addCountry: "ایک اور ملک شامل کریں",
      total: "کل",
      nightsAcross: "راتیں",
      destinations: "منزلوں میں",
      destination: "منزل",
      country: "ملک",
      selectCountry: "ملک منتخب کریں",
      addHotel: "ایک اور ہوٹل شامل کریں",
      removeDestination: "منزل ختم کریں",
      hotel: "ہوٹل",
      removeHotel: "ہوٹل ختم کریں",
      hotelName: "ہوٹل کا نام",
      hotelPlaceholder: "ہوٹل کا نام",
      pricePerNight: "فی رات قیمت",
      pricePlaceholder: "PKR فی رات",
      checkIn: "چیک اِن تاریخ",
      checkOut: "چیک آؤٹ تاریخ",
      nights: "راتیں",
      dateOrder: "چیک آؤٹ تاریخ چیک اِن کے بعد ہونی چاہیے۔",
    },
    step3: {
      step: "مرحلہ 3",
      title: "فلائٹ منزلیں اور ٹکٹ قیمت",
      description: "ہر فلائٹ لیگ شامل کریں اور فی مسافر ٹکٹ قیمت درج کریں۔",
      addFlight: "ایک اور فلائٹ شامل کریں",
      totalTicket: "کل ٹکٹ لاگت (تمام فلائٹس)",
      flight: "فلائٹ",
      removeFlight: "فلائٹ ختم کریں",
      airline: "ایئر لائن",
      selectAirline: "ایئر لائن منتخب کریں",
      from: "کہاں سے (روانگی)",
      selectDeparture: "روانگی کا شہر منتخب کریں",
      to: "کہاں تک (منزل)",
      selectDestination: "منزل منتخب کریں",
      date: "تاریخ",
      time: "وقت",
      ticketPrices: "ٹکٹ قیمتیں (PKR فی مسافر)",
      perAdult: "فی بالغ",
      perChild: "فی بچہ",
      perInfant: "فی شیرخوار",
      adultPlaceholder: "PKR فی بالغ",
      childPlaceholder: "PKR فی بچہ",
      infantPlaceholder: "PKR فی شیرخوار",
      adults: "بالغ",
      children: "بچے",
      infants: "شیرخوار",
      flightTotal: "فلائٹ کل",
    },
    review: {
      title: "اپنی ٹور کوٹیشن کا جائزہ لیں",
      description:
        "جمع کرنے سے پہلے تمام تفصیلات احتیاط سے دیکھ لیں۔ ہماری ٹیم 2 کاروباری گھنٹوں میں آپ سے رابطہ کرے گی۔",
      couponTitle: "کوپن کوڈ (اختیاری)",
      couponPlaceholder: "اگر کوپن کوڈ ہو تو درج کریں",
      couponNote: "کوپن ڈسکاؤنٹ دی فلائٹ سینٹر ٹیم دستی طور پر لگائے گی۔",
      customer: "کسٹمر تفصیلات",
      name: "نام",
      contact: "رابطہ",
      email: "ای میل",
      passengers: "مسافر",
      adults: "بالغ",
      children: "بچے",
      infants: "شیرخوار",
      age12: "عمر 12+",
      age2to11: "عمر 2 تا 11",
      under2: "2 سال سے کم",
      totalPassengers: "کل مسافر",
      countriesHotels: "ممالک اور ہوٹلز",
      selectedCountry: "منتخب ملک",
      hotelName: "ہوٹل کا نام",
      notProvided: "درج نہیں",
      checkInOut: "چیک اِن - چیک آؤٹ",
      nights: "راتیں",
      nightsLower: "راتیں",
      rate: "ریٹ",
      night: "رات",
      hotelCost: "ہوٹل لاگت",
      countryFallback: "ملک",
      subtotal: "ذیلی کل",
      totalHotelNights: "کل ہوٹل راتیں",
      totalHotelCost: "کل ہوٹل لاگت",
      flights: "فلائٹس",
      flight: "فلائٹ",
      airline: "ایئر لائن",
      date: "تاریخ",
      adultTickets: "بالغ ٹکٹس",
      childTickets: "بچوں کے ٹکٹس",
      infantTickets: "شیرخوار ٹکٹس",
      flightTotal: "فلائٹ کل",
      totalFlightCost: "کل فلائٹ لاگت",
      coupon: "کوپن",
      couponCode: "کوپن کوڈ",
      none: "نہیں",
      discountNote: "ڈسکاؤنٹ دی فلائٹ سینٹر ٹیم لگائے گی۔",
      totalSummary: "کل کوٹیشن خلاصہ",
      grandTotal: "گرینڈ ٹوٹل",
      estimateNote:
        "یہ آپ کے درج کیے گئے ریٹس کی بنیاد پر اندازاً کوٹیشن ہے۔ حتمی قیمت دی فلائٹ سینٹر ٹیم کنفرم کرے گی۔ ہوٹل اور فلائٹ دستیابی تبدیل ہو سکتی ہے۔",
    },
    success: {
      title: "ٹور کوٹیشن جمع ہو گئی!",
      description:
        "آپ کی ٹور پیکج کوٹیشن موصول ہو گئی ہے۔ ہماری ٹریول ٹیم 2 کاروباری گھنٹوں میں قیمت اور دستیابی کے ساتھ رابطہ کرے گی۔",
      reference: "ریفرنس نمبر",
      call: "ہم کال کریں گے",
      confirmation: "تصدیق بھیج دی گئی",
      returning: "ہوم پیج پر واپسی",
      goHome: "ابھی ہوم پر جائیں",
    },
  },
} as const;

export type TourErrorCopy = (typeof tourCopy)[keyof typeof tourCopy]["errors"];
export type TourStep2Copy = (typeof tourCopy)[keyof typeof tourCopy]["step2"];
export type TourStep3Copy = (typeof tourCopy)[keyof typeof tourCopy]["step3"];
export type TourReviewCopy = (typeof tourCopy)[keyof typeof tourCopy]["review"];
