export type CalculatorLocale = "en" | "ur";

export function isUrdu(locale: string) {
  return locale === "ur";
}

export const umrahCopy = {
  en: {
    steps: ["Details", "Flights", "Makkah", "Madinah", "Transport", "Review"],
    nav: {
      previous: "Previous",
      next: "Next Step ->",
      submit: "Submit Quotation",
      sending: "Sending...",
      submissionFailed: "Submission failed.",
      genericError: "Something went wrong. Please try again.",
    },
    errors: {
      airline: "Please select an airline.",
      departureCity: "Please select the departure city.",
      arrivalCity: "Please select the arrival city.",
      travelDate: "Please select a travel date.",
      hotelBlock: "Please add at least one hotel block.",
      roomType: "Please select a room type.",
      hotel: "Please select a hotel.",
      rooms: "Rooms must be at least 1.",
      checkIn: "Please select a check-in date.",
      checkOut: "Please select a check-out date.",
      dateOrder: "Check-out must be after check-in.",
      passengerName: "Please enter the passenger name.",
      contactNumber: "Please enter a valid contact number.",
      email: "Please enter a valid email address.",
      adults: "At least one adult passenger is required.",
      transportVisa: "Please select a transport and visa package.",
      exchangeRate: "Please enter a valid exchange rate.",
    },
    step1: {
      title: "Customer & Passenger Details",
      description:
        "Enter the lead passenger's contact information and total traveller count.",
      passengerName: "Passenger Name",
      passengerPlaceholder: "Enter full name",
      contactNumber: "Contact Number",
      email: "Email Address",
      emailPlaceholder: "you@example.com",
      decrease: "Decrease",
      increase: "Increase",
      passengers: {
        adults: ["Adults", "Age 12+"],
        children: ["Children", "Age 2-11"],
        infants: ["Infants", "Under 2 (no seat)"],
      },
    },
    step2: {
      title: "Flight Details",
      description: "Choose your preferred outbound and return routing for the quotation.",
      departure: "Departure Flight",
      return: "Return Flight",
      airline: "Airline",
      selectAirline: "Select airline",
      from: "From",
      to: "To",
      selectDeparture: "Select departure city",
      selectArrival: "Select arrival city",
      date: "Date",
      time: "Time",
    },
    hotel: {
      block: "Hotel Block",
      nights: "Nights",
      remove: "Remove hotel block",
      roomType: "Room Type",
      selectRoomType: "Select room type",
      hotel: "Hotel",
      selectHotel: "Select hotel",
      rooms: "Number of Rooms",
      checkIn: "Check-in Date",
      checkOut: "Check-out Date",
    },
    step3: {
      title: "Makkah Hotel Selection",
      description: "Add one or more hotel blocks for your Makkah stay.",
      city: "Makkah",
      add: "Add Another Hotel",
    },
    step4: {
      title: "Madinah Hotel Selection",
      description: "Add one or more hotel blocks for your Madinah stay.",
      city: "Madinah",
      add: "Add Another Madinah Hotel",
    },
    step5: {
      title: "Transport, Visa & Pricing",
      description: "Finalise your package preferences and estimated ticket pricing.",
      package: "Transport & Visa Package",
      selectPackage: "Select transport and visa package",
      selected: "selected",
      adultTicket: "Ticket Price per Adult (PKR)",
      childTicket: "Ticket Price per Child (PKR)",
      infantTicket: "Ticket Price per Infant (PKR)",
      exchangeRate: "Exchange Rate (1 SAR = ? PKR)",
      exchangePlaceholder: "e.g. 75",
      coupon: "Coupon Code (optional)",
      couponPlaceholder: "Enter coupon code (if any)",
      couponNote: "Coupon discounts are applied manually by The Flight Centre team.",
      totals: "Running Totals",
      totalPassengers: "Total Passengers",
      transportCost: "Transport Cost",
      ticketAdults: "Ticket (Adults)",
      ticketChildren: "Ticket (Children)",
      ticketInfants: "Ticket (Infants)",
      hotelNote: "Final hotel pricing will be confirmed by The Flight Centre team.",
    },
    review: {
      title: "Review Your Quotation",
      description:
        "Please review all details before submitting. Once submitted, our team will contact you within 2 hours.",
      customer: "Customer Details",
      name: "Name",
      contact: "Contact",
      email: "Email",
      passengers: "Passengers",
      adults: "Adults",
      children: "Children",
      infants: "Infants",
      totalPassengers: "Total Passengers",
      flights: "Flight Details",
      departure: "Departure",
      return: "Return",
      airline: "Airline",
      from: "From",
      to: "To",
      date: "Date",
      time: "Time",
      makkahHotels: "Makkah Hotels",
      madinahHotels: "Madinah Hotels",
      hotel: "Hotel",
      roomType: "Room Type",
      rooms: "Rooms",
      checkIn: "Check-in",
      checkOut: "Check-out",
      nights: "Nights",
      totalMakkahNights: "Total Makkah Nights",
      totalMadinahNights: "Total Madinah Nights",
      transportPricing: "Transport, Visa & Pricing",
      transportPackage: "Transport Package",
      transportCost: "Transport Cost",
      exchangeRate: "Exchange Rate",
      ticketAdults: "Ticket (Adults)",
      ticketChildren: "Ticket (Children)",
      ticketInfants: "Ticket (Infants)",
      couponCode: "Coupon Code",
      totalSummary: "Total Summary",
      totalTicketCost: "Total Ticket Cost",
      note:
        "Note: Hotel accommodation pricing will be confirmed separately by The Flight Centre team based on availability and room selection. The above reflects ticket and transport costs only.",
      hotelNumber: "Hotel",
    },
    success: {
      title: "Quotation Submitted!",
      description:
        "Your Umrah quotation request has been received. Our team will call you within 2 hours.",
      reference: "Reference Number",
      call: "We'll call",
      confirmation: "Confirmation sent to",
      returning: "Returning to homepage in",
      goHome: "Go Home Now",
    },
  },
  ur: {
    steps: ["تفصیلات", "فلائٹس", "مکہ", "مدینہ", "ٹرانسپورٹ", "جائزہ"],
    nav: {
      previous: "واپس",
      next: "اگلا مرحلہ ←",
      submit: "کوٹیشن جمع کریں",
      sending: "بھیجا جا رہا ہے...",
      submissionFailed: "درخواست جمع نہیں ہو سکی۔",
      genericError: "کچھ مسئلہ پیش آیا۔ براہِ کرم دوبارہ کوشش کریں۔",
    },
    errors: {
      airline: "براہِ کرم ایئر لائن منتخب کریں۔",
      departureCity: "براہِ کرم روانگی کا شہر منتخب کریں۔",
      arrivalCity: "براہِ کرم آمد کا شہر منتخب کریں۔",
      travelDate: "براہِ کرم سفر کی تاریخ منتخب کریں۔",
      hotelBlock: "براہِ کرم کم از کم ایک ہوٹل بلاک شامل کریں۔",
      roomType: "براہِ کرم روم ٹائپ منتخب کریں۔",
      hotel: "براہِ کرم ہوٹل منتخب کریں۔",
      rooms: "کمروں کی تعداد کم از کم 1 ہونی چاہیے۔",
      checkIn: "براہِ کرم چیک اِن تاریخ منتخب کریں۔",
      checkOut: "براہِ کرم چیک آؤٹ تاریخ منتخب کریں۔",
      dateOrder: "چیک آؤٹ تاریخ چیک اِن کے بعد ہونی چاہیے۔",
      passengerName: "براہِ کرم مسافر کا نام درج کریں۔",
      contactNumber: "براہِ کرم درست رابطہ نمبر درج کریں۔",
      email: "براہِ کرم درست ای میل ایڈریس درج کریں۔",
      adults: "کم از کم ایک بالغ مسافر ضروری ہے۔",
      transportVisa: "براہِ کرم ٹرانسپورٹ اور ویزا پیکج منتخب کریں۔",
      exchangeRate: "براہِ کرم درست ایکسچینج ریٹ درج کریں۔",
    },
    step1: {
      title: "کسٹمر اور مسافر کی تفصیلات",
      description: "مرکزی مسافر کی رابطہ معلومات اور کل مسافروں کی تعداد درج کریں۔",
      passengerName: "مسافر کا نام",
      passengerPlaceholder: "پورا نام درج کریں",
      contactNumber: "رابطہ نمبر",
      email: "ای میل ایڈریس",
      emailPlaceholder: "you@example.com",
      decrease: "کم کریں",
      increase: "زیادہ کریں",
      passengers: {
        adults: ["بالغ", "عمر 12+"],
        children: ["بچے", "عمر 2 تا 11"],
        infants: ["شیرخوار", "2 سال سے کم، سیٹ کے بغیر"],
      },
    },
    step2: {
      title: "فلائٹ کی تفصیلات",
      description: "کوٹیشن کے لیے روانگی اور واپسی کا پسندیدہ روٹ منتخب کریں۔",
      departure: "روانگی کی فلائٹ",
      return: "واپسی کی فلائٹ",
      airline: "ایئر لائن",
      selectAirline: "ایئر لائن منتخب کریں",
      from: "کہاں سے",
      to: "کہاں تک",
      selectDeparture: "روانگی کا شہر منتخب کریں",
      selectArrival: "آمد کا شہر منتخب کریں",
      date: "تاریخ",
      time: "وقت",
    },
    hotel: {
      block: "ہوٹل بلاک",
      nights: "راتیں",
      remove: "ہوٹل بلاک ختم کریں",
      roomType: "روم ٹائپ",
      selectRoomType: "روم ٹائپ منتخب کریں",
      hotel: "ہوٹل",
      selectHotel: "ہوٹل منتخب کریں",
      rooms: "کمروں کی تعداد",
      checkIn: "چیک اِن تاریخ",
      checkOut: "چیک آؤٹ تاریخ",
    },
    step3: {
      title: "مکہ ہوٹل سلیکشن",
      description: "مکہ قیام کے لیے ایک یا زیادہ ہوٹل بلاکس شامل کریں۔",
      city: "مکہ",
      add: "ایک اور ہوٹل شامل کریں",
    },
    step4: {
      title: "مدینہ ہوٹل سلیکشن",
      description: "مدینہ قیام کے لیے ایک یا زیادہ ہوٹل بلاکس شامل کریں۔",
      city: "مدینہ",
      add: "ایک اور مدینہ ہوٹل شامل کریں",
    },
    step5: {
      title: "ٹرانسپورٹ، ویزا اور قیمت",
      description: "اپنے پیکج کی ترجیحات اور اندازاً ٹکٹ قیمت مکمل کریں۔",
      package: "ٹرانسپورٹ اور ویزا پیکج",
      selectPackage: "ٹرانسپورٹ اور ویزا پیکج منتخب کریں",
      selected: "منتخب",
      adultTicket: "فی بالغ ٹکٹ قیمت (PKR)",
      childTicket: "فی بچہ ٹکٹ قیمت (PKR)",
      infantTicket: "فی شیرخوار ٹکٹ قیمت (PKR)",
      exchangeRate: "ایکسچینج ریٹ (1 SAR = ? PKR)",
      exchangePlaceholder: "مثلاً 75",
      coupon: "کوپن کوڈ (اختیاری)",
      couponPlaceholder: "اگر کوپن ہو تو درج کریں",
      couponNote: "کوپن ڈسکاؤنٹ دی فلائٹ سینٹر ٹیم دستی طور پر لگائے گی۔",
      totals: "اب تک کا حساب",
      totalPassengers: "کل مسافر",
      transportCost: "ٹرانسپورٹ لاگت",
      ticketAdults: "ٹکٹ (بالغ)",
      ticketChildren: "ٹکٹ (بچے)",
      ticketInfants: "ٹکٹ (شیرخوار)",
      hotelNote: "حتمی ہوٹل قیمت دی فلائٹ سینٹر ٹیم کنفرم کرے گی۔",
    },
    review: {
      title: "اپنی کوٹیشن کا جائزہ لیں",
      description:
        "جمع کرنے سے پہلے تمام تفصیلات دیکھ لیں۔ جمع ہونے کے بعد ہماری ٹیم 2 گھنٹے میں آپ سے رابطہ کرے گی۔",
      customer: "کسٹمر تفصیلات",
      name: "نام",
      contact: "رابطہ",
      email: "ای میل",
      passengers: "مسافر",
      adults: "بالغ",
      children: "بچے",
      infants: "شیرخوار",
      totalPassengers: "کل مسافر",
      flights: "فلائٹ تفصیلات",
      departure: "روانگی",
      return: "واپسی",
      airline: "ایئر لائن",
      from: "کہاں سے",
      to: "کہاں تک",
      date: "تاریخ",
      time: "وقت",
      makkahHotels: "مکہ ہوٹلز",
      madinahHotels: "مدینہ ہوٹلز",
      hotel: "ہوٹل",
      roomType: "روم ٹائپ",
      rooms: "کمرے",
      checkIn: "چیک اِن",
      checkOut: "چیک آؤٹ",
      nights: "راتیں",
      totalMakkahNights: "کل مکہ راتیں",
      totalMadinahNights: "کل مدینہ راتیں",
      transportPricing: "ٹرانسپورٹ، ویزا اور قیمت",
      transportPackage: "ٹرانسپورٹ پیکج",
      transportCost: "ٹرانسپورٹ لاگت",
      exchangeRate: "ایکسچینج ریٹ",
      ticketAdults: "ٹکٹ (بالغ)",
      ticketChildren: "ٹکٹ (بچے)",
      ticketInfants: "ٹکٹ (شیرخوار)",
      couponCode: "کوپن کوڈ",
      totalSummary: "کل خلاصہ",
      totalTicketCost: "کل ٹکٹ لاگت",
      note:
        "نوٹ: ہوٹل رہائش کی قیمت دستیابی اور روم سلیکشن کے مطابق دی فلائٹ سینٹر ٹیم الگ سے کنفرم کرے گی۔ اوپر صرف ٹکٹ اور ٹرانسپورٹ لاگت شامل ہے۔",
      hotelNumber: "ہوٹل",
    },
    success: {
      title: "کوٹیشن جمع ہو گئی!",
      description:
        "آپ کی عمرہ کوٹیشن درخواست موصول ہو گئی ہے۔ ہماری ٹیم 2 گھنٹے میں آپ کو کال کرے گی۔",
      reference: "ریفرنس نمبر",
      call: "ہم کال کریں گے",
      confirmation: "تصدیق بھیج دی گئی",
      returning: "ہوم پیج پر واپسی",
      goHome: "ابھی ہوم پر جائیں",
    },
  },
} as const;

export type UmrahErrorCopy = (typeof umrahCopy)[keyof typeof umrahCopy]["errors"];
export type UmrahStep2Copy = (typeof umrahCopy)[keyof typeof umrahCopy]["step2"];
export type UmrahReviewCopy = (typeof umrahCopy)[keyof typeof umrahCopy]["review"];
